import { useEffect, useState } from 'react';
import type { IssueSeverity, IssueStatus, ProjectIssue } from '../../../../services/api';
import { statusLabel } from './issueUtils';
export type IssueDraft={title:string;description:string;severity:IssueSeverity;status:IssueStatus};
type Props={issues:ProjectIssue[];selected:ProjectIssue|null;creating:boolean;filter:IssueStatus|'ALL';busy:boolean;onFilter:(v:IssueStatus|'ALL')=>void;onSave:(draft:IssueDraft)=>void;onDelete:(id:string)=>void;onSelect:(issue:ProjectIssue)=>void;onClose:()=>void};
export function IssuePanel({issues,selected,creating,filter,busy,onFilter,onSave,onDelete,onSelect,onClose}:Props){
 const [draft,setDraft]=useState<IssueDraft>({title:'',description:'',severity:'MEDIUM',status:'OPEN'});
 useEffect(()=>setDraft(selected?{title:selected.title,description:selected.description??'',severity:selected.severity,status:selected.status}:{title:'',description:'',severity:'MEDIUM',status:'OPEN'}),[selected,creating]);
 return <div className="absolute bottom-3 right-3 z-30 w-[min(390px,calc(100%-24px))] rounded-2xl border border-rose-500/40 bg-slate-950/95 text-slate-100 shadow-2xl backdrop-blur-xl"><div className="flex justify-between border-b border-slate-800 px-4 py-3"><div><div className="text-[11px] font-bold uppercase tracking-[.14em] text-rose-300">Vấn đề / Issue</div><div className="text-[9px] text-slate-500">{creating?'Tạo pin tại vị trí đã chọn':selected?'Chi tiết vấn đề':`${issues.length} vấn đề`}</div></div><button onClick={onClose} className="h-7 w-7 rounded border border-slate-700">×</button></div>
 <div className="p-4"><div className="mb-3 grid grid-cols-4 gap-1">{(['ALL','OPEN','IN_PROGRESS','RESOLVED'] as const).map(v=><button key={v} onClick={()=>onFilter(v)} className={`rounded px-1 py-1.5 text-[9px] ${filter===v?'bg-rose-500 font-bold text-white':'bg-slate-900 text-slate-400'}`}>{v==='ALL'?'Tất cả':statusLabel(v)}</button>)}</div>
 {(creating||selected)?<div className="space-y-2"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Tiêu đề" className="h-9 w-full rounded border border-slate-700 bg-slate-900 px-2 text-xs"/><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Mô tả" rows={3} className="w-full rounded border border-slate-700 bg-slate-900 p-2 text-xs"/><div className="grid grid-cols-2 gap-2"><select value={draft.severity} onChange={e=>setDraft({...draft,severity:e.target.value as IssueSeverity})} className="h-8 rounded bg-slate-900 text-xs"><option value="LOW">Thấp</option><option value="MEDIUM">Trung bình</option><option value="HIGH">Cao</option><option value="CRITICAL">Nghiêm trọng</option></select><select value={draft.status} disabled={creating} onChange={e=>setDraft({...draft,status:e.target.value as IssueStatus})} className="h-8 rounded bg-slate-900 text-xs"><option value="OPEN">Mở</option><option value="IN_PROGRESS">Đang xử lý</option><option value="RESOLVED">Đã xử lý</option></select></div>{selected&&<div className="text-[9px] text-slate-500">Tạo lúc {new Date(selected.createdAt).toLocaleString('vi-VN')}</div>}<div className="flex gap-2"><button disabled={busy||!draft.title.trim()} onClick={()=>onSave(draft)} className="h-8 flex-1 rounded bg-rose-500 text-[10px] font-bold disabled:opacity-40">{creating?'Lưu issue':'Cập nhật'}</button>{selected&&<button disabled={busy} onClick={()=>onDelete(selected.id)} className="rounded border border-red-700 px-3 text-[10px] text-red-300">Xóa</button>}</div></div>:<div className="max-h-52 space-y-1 overflow-auto">{issues.map(issue=><button key={issue.id} onClick={()=>onSelect(issue)} className="flex w-full items-center justify-between rounded bg-slate-900 px-2 py-2 text-left text-xs"><span className="truncate">{issue.title}</span><span className="ml-2 text-[9px] text-slate-500">{statusLabel(issue.status)}</span></button>)}</div>}
 </div></div>;
}
