import path from 'path';
import fs from 'fs-extra';
import dotenv from 'dotenv';
dotenv.config();

import { spawn } from 'child_process';
import { uploadProjectFilesToR2 } from './src/r2Service';
import { PrismaClient } from './src/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const pythonCmd = 'C:\\Users\\duong\\AppData\\Local\\Programs\\Python\\Python312\\python.exe';
const pythonScript = 'c:\\Users\\duong\\Web GIS\\web-gis-platform\\tools\\3d-optimizer\\src\\build_optimized.py';

async function runCommand(cmd: string, args: string[]): Promise<number> {
  return new Promise((resolve) => {
    console.log(`Executing: ${cmd} ${args.join(' ')}`);
    const proc = spawn(cmd, args, { stdio: 'inherit' });
    proc.on('close', (code) => resolve(code ?? 1));
  });
}

async function main() {
  const projectId = '0261fee6-221e-49c9-b23c-196746f37dd6';
  const inputDir = 'C:\\Users\\duong\\3dmaping\\QuyNhon_31072026_process';
  const outputDir = 'C:\\Users\\duong\\3dmaping\\QuyNhon_31072026_output';
  const epsg = 32649;

  console.log(`\n==================================================`);
  console.log(`🚀 PROCESSING POINT CLOUD ONLY: QUY NHON PROJECT`);
  console.log(`Project ID: ${projectId}`);
  console.log(`Input: ${inputDir}`);
  console.log(`Output: ${outputDir}`);
  console.log(`EPSG: ${epsg}`);
  console.log(`==================================================\n`);

  await fs.ensureDir(outputDir);

  // 1. Run Python build_optimized.py --skip-dom --skip-model
  const exitCode = await runCommand(pythonCmd, [
    pythonScript,
    inputDir,
    '-o', outputDir,
    '--epsg', epsg.toString(),
    '--skip-dom',
    '--skip-model'
  ]);

  if (exitCode !== 0) {
    console.error(`❌ Python script failed with exit code: ${exitCode}`);
    process.exit(1);
  }

  console.log(`\n✅ Point cloud generation finished!`);

  // 2. Upload to Cloudflare R2
  console.log(`\n☁️ Uploading Point Cloud to Cloudflare R2...`);
  const urls = await uploadProjectFilesToR2(projectId, outputDir);
  console.log(`Uploaded URLs:`, JSON.stringify(urls, null, 2));

  if (!urls.pointCloudUrl) {
    console.error(`❌ pointCloudUrl was not generated by uploadProjectFilesToR2!`);
    process.exit(1);
  }

  // 3. Update Database
  console.log(`\n💾 Updating database record...`);
  await prisma.project.update({
    where: { id: projectId },
    data: {
      pointCloudId: urls.pointCloudUrl
    }
  });

  console.log(`\n🎉 SUCCESS! Project ${projectId} updated with pointCloudId = ${urls.pointCloudUrl}`);
  await prisma.$disconnect();
  await pool.end();
}

main().catch(async (e) => {
  console.error(e);
  await prisma.$disconnect();
  await pool.end();
  process.exit(1);
});
